FROM python:3.12-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    && apt-get install -y coreutils \
    && rm -rf /var/lib/apt/lists/*

COPY create_dirs.py /usr/local/bin/create_dirs.py
RUN chmod +x /usr/local/bin/create_dirs.py

ENTRYPOINT ["/usr/local/bin/create_dirs.py"]