#!/bin/bash

[ -n "$1" ] && TAG_VERSION="$1"

REGISTRY=us-docker.pkg.dev
REPOSITORY=jarvice/images
IMAGE=idmapper
CREATE_DIRS_IMAGE=idmapper-create-dirs
PLATFORMS="linux/amd64,linux/ppc64le,linux/arm64"

BUILDER=multiarch

docker buildx create --name $BUILDER --use

export DOCKER_CLI_EXPERIMENTAL=enabled
docker buildx build --rm \
    --builder $BUILDER \
    --platform $PLATFORMS --push \
    -t $REGISTRY/$REPOSITORY/$IMAGE:${TAG_VERSION} \
    -f Dockerfile .

docker buildx build --rm \
    --builder $BUILDER \
    --platform $PLATFORMS --push \
    -t $REGISTRY/$REPOSITORY/$CREATE_DIRS_IMAGE:${TAG_VERSION} \
    -f Dockerfile.create_dirs .
