apiVersion: apps/v1
kind: Deployment
metadata:
  name: jarvice-idmapper
  labels:
    app: jarvice-idmapper
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jarvice-idmapper
  template:
    metadata:
      labels:
        app: jarvice-idmapper
    spec:
      containers:
      - name: idmapper
        image: nimbix/idmapper
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: homes
          mountPath: /home
          readOnly: true
        resources:
          limits:
            cpu: "100m"
            memory: 128Mi
          requests:
            cpu: "100m"
            memory: 128Mi
      volumes:
      - name: homes
        nfs:
          server: $NFS_SERVER
          path: $NFS_PATH
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/jarvice-system
        operator: Exists
      nodeSelector:
        node-role.kubernetes.io/jarvice-system: ""
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jarvice-idmapper
  name: jarvice-idmapper
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: jarvice-idmapper
  sessionAffinity: None
  type: ClusterIP
status:
    loadBalancer: {}
